-- DBAS-5206-02 Group Project CREATE script by Group 6
-- Bei Jia, Chiao-Yun Chung, Vishwa Patel, Yuqi Zhou
use master

-- Create database
DROP DATABASE IF EXISTS DB_LRCH;
CREATE DATABASE DB_LRCH;
go
-- Use database
USE DB_LRCH;
go
DROP TABLE IF EXISTS FINANCIAL_STATUS;
CREATE TABLE FINANCIAL_STATUS (
FINANCIAL_ID INT PRIMARY KEY IDENTITY,
FINANCIAL_TYPE VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS PHYSICIAN;
CREATE TABLE PHYSICIAN (
PHYSICIAN_NO INT PRIMARY KEY IDENTITY,
PHYSICIAN_FIRST_NAME VARCHAR(50) NOT NULL,
PHYSICIAN_LAST_NAME VARCHAR(50) NOT NULL,
SPECIALTY VARCHAR(50) NOT NULL,
PHYSICIAN_PHONE VARCHAR(15) NOT NULL
);

DROP TABLE IF EXISTS PATIENT;
CREATE TABLE PATIENT (

--PATIENT_NO INT PRIMARY KEY IDENTITY,
PATIENT_NO INT PRIMARY KEY IDENTITY(10000,1),

--Remove physician id
--PHYSICIAN_NO INT NOT NULL FOREIGN KEY REFERENCES PHYSICIAN(PHYSICIAN_NO),
PATIENT_FIRST_NAME VARCHAR(50) NOT NULL,
PATIENT_LAST_NAME VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
PHONE VARCHAR(15) NOT NULL,
CITY_PROV_PC VARCHAR(100) NOT NULL,
SEX CHAR(1) NOT NULL,
HCN VARCHAR(15) NOT NULL,
EXTENSION VARCHAR(10),
LAST_DISCHARGE_DATE DATE
);

DROP TABLE IF EXISTS PRESCRIPTION;
CREATE TABLE PRESCRIPTION (
PRES_ID INT PRIMARY KEY IDENTITY,
PHYSICIAN_ID INT NOT NULL FOREIGN KEY REFERENCES PHYSICIAN(PHYSICIAN_NO),
PATIENT_ID INT NOT NULL FOREIGN KEY REFERENCES PATIENT(PATIENT_NO),
PRES_DATE DATE NOT NULL,
PRES_MEDICATION VARCHAR(50) NOT NULL,
PRES_DOSAGE VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS ROOM;
CREATE TABLE ROOM (
ROOM_NUMBER INT NOT NULL PRIMARY KEY IDENTITY,
ROOM_TYPE VARCHAR(50) NOT NULL,
ROOM_EXTENSION VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS BED;
CREATE TABLE BED (
BED_ID INT NOT NULL PRIMARY KEY IDENTITY,
ROOM_NUMBER INT NOT NULL FOREIGN KEY REFERENCES ROOM(ROOM_NUMBER),
BED_NUMBER VARCHAR NOT NULL
);

DROP TABLE IF EXISTS COST_CENTRE;
CREATE TABLE COST_CENTRE (
COST_CENTRE_ID INT NOT NULL PRIMARY KEY IDENTITY,
DESCRIPTION VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS ADMISSION;
CREATE TABLE ADMISSION (
ADMISSION_ID INT NOT NULL PRIMARY KEY IDENTITY,
PATIENT_ID INT NOT NULL FOREIGN KEY REFERENCES PATIENT(PATIENT_NO),
BED_ID INT NOT NULL FOREIGN KEY REFERENCES BED(BED_ID),
ADMISSION_DATE DATE NOT NULL,
DISCHARGE_DATE DATE NOT NULL,
APPOINTMENT BIT,
NOTE VARCHAR(200)
);



DROP TABLE IF EXISTS ITEM;
CREATE TABLE ITEM (
ITEM_CODE INT NOT NULL PRIMARY KEY IDENTITY,
COST_CENTRE_ID INT NOT NULL FOREIGN KEY REFERENCES COST_CENTRE(COST_CENTRE_ID),
COST SMALLMONEY NOT NULL
);

DROP TABLE IF EXISTS BILL;
CREATE TABLE BILL (
BILL_ID INT NOT NULL PRIMARY KEY IDENTITY,
ADMISSION_ID INT NOT NULL FOREIGN KEY REFERENCES ADMISSION(ADMISSION_ID),
BILL_DATE DATE NOT NULL
);

DROP TABLE IF EXISTS CHARGE_ITEM;
CREATE TABLE CHARGE_ITEM (
ITEM_ID INT NOT NULL PRIMARY KEY IDENTITY,
ITEM_CODE INT NOT NULL FOREIGN KEY REFERENCES ITEM(ITEM_CODE),
BILL_ID INT NOT NULL FOREIGN KEY REFERENCES BILL(BILL_ID),
FINANCIAL_ID INT NOT NULL FOREIGN KEY REFERENCES FINANCIAL_STATUS(FINANCIAL_ID),
ADMISSION_ID INT NOT NULL FOREIGN KEY REFERENCES ADMISSION(ADMISSION_ID),
DESCRIPTION VARCHAR(50) NOT NULL,
QUANTITY INT NOT NULL,
UNIT_PRICE SMALLMONEY NOT NULL,
DATE DATE NOT NULL
);

DROP TABLE IF EXISTS PAYMENT;
CREATE TABLE PAYMENT (
PAYMENT_ID INT NOT NULL PRIMARY KEY IDENTITY,
BILL_ID INT NOT NULL FOREIGN KEY REFERENCES BILL(BILL_ID),
PAYMENT_DATE DATE NOT NULL,
PAID_AMOUNT FLOAT NOT NULL
);

DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST (
TEST_ID INT NOT NULL PRIMARY KEY IDENTITY,
PATIENT_ID INT NOT NULL FOREIGN KEY REFERENCES PATIENT(PATIENT_no),
PHYSICIAN_ID INT NOT NULL FOREIGN KEY REFERENCES PHYSICIAN(PHYSICIAN_NO),
TEST_DATE DATE NOT NULL,
TEST_TYPE VARCHAR(50) NOT NULL,
RESULT VARCHAR(50) NOT NULL
);

-- Insert records into PATIENT table 

INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Gary', 'Horwath', '390 Yonge St', '416-722-5329', 'North York, ON, M3S 6N8', 'M', 'EEG 008 977', '86774222', '2022-09-16');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Nicole', 'Shirsinger', '43 Fairwell Dr', '289-366-3769', 'Oshawa, ON, L6R 4I8', 'F', 'UIU 343 908', '23498703', '2023-01-02');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Sarah', 'Harris', '11 Nash Rd', '289-511-9223', 'Courtice, ON, L1U 8F3', 'F', 'ABD 556 791', '33445890', '2023-01-17');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION) 
	VALUES ('Matt', 'Garrison', '3445 Tuanton Rd.', '905-906-9335', 'Oshawa, ON, M0G G5K', 'M', 'KIT 549 098', '');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Chris', 'Baweja', '21 Gibb St', '905-578-5643', 'Oshawa, ON, L2J 5I4', 'M', 'XXR 443 770', '84778243', '2022-11-09');

INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Lindsay', 'Denton', '255 Sheppard Ave', '416-496-8866', 'Toronto, ON, M1R 6T9', 'F', 'APC 229 341', '30482648', '');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Nancy', 'Talaba', '208 Nash Rd', '289-978-3225', 'Courtice, ON, L1S 2S2', 'F', 'RRT 893 892', '28462933', '2023-01-11');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Moon', 'Liu', 'Markham Rd.', '905-337-5897', 'Markham, ON, N4U 7T6', 'F', 'SER 672 230', '02847620', '');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Mike', 'Walsh', '50 Holt Rd', '289-255-2556', 'Clarington, ON, L3A 9H4', 'M', 'JKU 905 432', '40371895', '2020-08-04');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Larry', 'Hausonn', '12 Bowmanville Ave', '905-978-2560', 'Bowmanville, ON, K6I 0F0', 'M', 'KJW 902 111', '49210578', '2018-12-23');

INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Amy', 'Wong', '7th St.', '416-935-9227', 'Markham, ON, N4S 2S3', 'F', 'MKX 909 115', '99068234', '');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Emily', 'Lindsey', '5 Clement Court', '416-924-0097', 'Richmond Hill, ON, H5H 9K6', 'F', 'CDU 575 219', '59215027', '2023-02-23');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Carl', 'Altman', '3004 King St.', '905-211-1918', 'Oshawa, ON, L9Y 4G4', 'M', 'NHY 367 998', '78112083', '');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Cindy', 'Clarkeson', '45 Trulls Rd', '289-219-2873', 'Courtice, ON, L1S 7B9', 'O', 'OKD 773 783', '09299975', '2021-06-29');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('David', 'Lee', '456 Oak St', '613-555-9775', 'Vancouver, BC, V1V 7J8', 'M', 'DLJ 456 220', '82001102', '2022-04-05');

INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Mary', 'Smith', '981 Pinecorn St', '905-115-2976', 'Niagara Falls, ON, R2H 5X1', 'F', 'MSS 329 651', '29371047', '');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Teddy', 'Williams', '803 Birch Ave', '416-904-998', 'Toronto, ON, S7M 4C9', 'M', 'RWB 034 033', '60017847', '2022-10-01');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Jenn', 'Zhai', '606 Sheppard Ave', '416-779-2288', 'North York, ON, M1E 2N1', 'F', 'GBE 624 690', '51014975', '2019-03-31');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Joe', 'Layton', '506 Adelaide Ave W', '289-753-8940', 'Oshawa, ON, S8J 8E3', 'M', 'JHC 409 789', '9041857', '');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Kenny', 'Patel', '5 Bailey St.', '905-201-0056', 'Pickering, ON, D1U 0E8', 'M', 'CVR 990 114', '71398587', '2021-11-07');

INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('James', 'Tran', '738 Lakeshore Blvd', '416-498-3755', 'Toronto, ON, M4V 4G6', 'M', 'KJJ 543 570', '00961392', '2019-08-15');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Be', 'Pham', '29 Fort York Blvd', '416-613-6233', 'Toronto, ON, M5L 9B3', 'F', 'DLW 901 397', '04375811', '');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Angela', 'Rusmusson', '798 Division St', '289-993-8004', 'Oshawa, ON, J8K 8W1', 'F', 'SCI 696 595', '09519472', '2017-11-22');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Harry', 'Pullman', '54 Aberdeen St.', '905-307-7724', 'Oshawa, ON, L8L 9G5', 'M', 'UFY 320 874', '59788325', '');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Maggie', 'Patel', '95 Dixon Rd', '416-766-7943', 'Mississauga, ON, H8G 4J2', 'F', 'JSJ 454 753', '09215634', '');

INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Helen', 'Hukulak', '875 Bassett Ave', '905-334-3701', 'Whitby, ON, S3E 0B6', 'F', 'HJC 771 665', '10522845', '2023-01-09');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Marc', 'Sizemore', '70 Wallace Dr', '905-056-1557', 'Ajax, ON, I3Y 8X5', 'M', 'ZET 151 457', '95878896', '2022-05-22');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Ryan', 'Chang', '323 Whitburn St.', '905-297-9372', 'Whitby, ON, S2D 0N7', 'M', 'CSR 993 605', '59269503', '2022-03-06');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Elizabeth', 'Roberts', '13 Lawson Rd', '416-243-7844', 'Scarborough, ON, D8H 3V3', 'F', 'NNE 393 740', '90175938', '');
INSERT INTO PATIENT(PATIENT_FIRST_NAME, PATIENT_LAST_NAME, ADDRESS, PHONE, CITY_PROV_PC, SEX, HCN, EXTENSION, LAST_DISCHARGE_DATE) 
	VALUES ('Zoe', 'Albiani', '20 Waterloo Ct.', '905-876-7660', 'Oshawa, ON, L1H 8A7', 'F', 'BAU 908 945', '33470801', '2021-07-18');

SELECT * FROM PATIENT;

-- Insert records into PHYSICIAN table 

INSERT INTO PHYSICIAN(PHYSICIAN_FIRST_NAME, PHYSICIAN_LAST_NAME, SPECIALTY, PHYSICIAN_PHONE) 
	VALUES ('Sabra', 'Mueller', 'GI', '416-299-5311');
INSERT INTO PHYSICIAN(PHYSICIAN_FIRST_NAME, PHYSICIAN_LAST_NAME, SPECIALTY, PHYSICIAN_PHONE) 
	VALUES ('Henry', 'Hastings', 'Endocrinology', '289-455-6609');
INSERT INTO PHYSICIAN(PHYSICIAN_FIRST_NAME, PHYSICIAN_LAST_NAME, SPECIALTY, PHYSICIAN_PHONE) 
	VALUES ('Kristen', 'Eversman', 'Oncology', '905-005-8777');
INSERT INTO PHYSICIAN(PHYSICIAN_FIRST_NAME, PHYSICIAN_LAST_NAME, SPECIALTY, PHYSICIAN_PHONE) 
	VALUES ('Ben', 'Hoo', 'Cardiology', '905-005-8802');
INSERT INTO PHYSICIAN(PHYSICIAN_FIRST_NAME, PHYSICIAN_LAST_NAME, SPECIALTY, PHYSICIAN_PHONE) 
	VALUES ('Greg', 'Jenson', 'Orthopedics', '416-927-1205');

INSERT INTO PHYSICIAN(PHYSICIAN_FIRST_NAME, PHYSICIAN_LAST_NAME, SPECIALTY, PHYSICIAN_PHONE) 
	VALUES ('Nicole', 'Yun', 'dermatology', '289-336-6336');
INSERT INTO PHYSICIAN(PHYSICIAN_FIRST_NAME, PHYSICIAN_LAST_NAME, SPECIALTY, PHYSICIAN_PHONE) 
	VALUES ('David', 'Logan', 'Neurology', '416-486-5932');
INSERT INTO PHYSICIAN(PHYSICIAN_FIRST_NAME, PHYSICIAN_LAST_NAME, SPECIALTY, PHYSICIAN_PHONE) 
	VALUES ('Olivia', 'Dadmar', 'OBGYN', '289-400-7900');
INSERT INTO PHYSICIAN(PHYSICIAN_FIRST_NAME, PHYSICIAN_LAST_NAME, SPECIALTY, PHYSICIAN_PHONE) 
	VALUES ('Daniel', 'Stillwell', 'General Surgeon', '905-678-8970');
INSERT INTO PHYSICIAN(PHYSICIAN_FIRST_NAME, PHYSICIAN_LAST_NAME, SPECIALTY, PHYSICIAN_PHONE) 
	VALUES ('Grace', 'Shang', 'Pneumology', '905-315-2447');

SELECT * FROM PHYSICIAN;



-- Insert records to ROOM table

INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('SEMI-PRIVATE', '3077');
INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('SEMI-PRIVATE', '3079');
INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('PRIVATE', '3112');
INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('W3', '3053');
INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('W3', '3054');

INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('W3', '3057');
INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('W4', '3058');
INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('W4', '3060');
INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('SEMI-PRIVATE', '3081');
INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('W4', '3061');

INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('W4', '3062');
INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('IC', '3064');
INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('PRIVATE', '3119');
INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('W3', '3066');
INSERT INTO ROOM(ROOM_TYPE, ROOM_EXTENSION) 
	VALUES ('IC', '3067');

SELECT * FROM ROOM;

-- Insert records to BED table

INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (1, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (1, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES ( 2, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (2, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (3, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (4, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (4, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (4, 'C');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (4, 'D');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (5, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (5, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (5, 'C');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (5, 'D');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (6, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (6, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (6, 'C');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (6, 'D');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (7, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (7, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (7, 'C');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (7, 'D');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (8, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (8, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (8, 'C');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (8, 'D');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (9, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (9, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (10, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (10, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (10, 'C');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (10, 'D');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (11, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (11, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (11, 'C');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (11, 'D');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (12, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (12, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (12, 'C');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (12, 'D');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (13, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (14, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (14, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (14, 'C');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (14, 'D');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (15, 'A');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (15, 'B');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (15, 'C');
INSERT INTO BED(ROOM_NUMBER, BED_NUMBER) 
	VALUES (15, 'D');

SELECT * FROM BED;
-- Insert records to ADMISSION table

INSERT INTO ADMISSION(PATIENT_ID, BED_ID, ADMISSION_DATE, DISCHARGE_DATE, APPOINTMENT,NOTE) 
	VALUES (10002, 9, '2021-04-04', '2021-04-20',1,'NOTE:');
INSERT INTO ADMISSION(PATIENT_ID, BED_ID, ADMISSION_DATE, DISCHARGE_DATE, APPOINTMENT,NOTE) 
	VALUES (10003, 3, '2023-04-01', '2023-04-10',1,'NOTE:');
INSERT INTO ADMISSION(PATIENT_ID, BED_ID, ADMISSION_DATE, DISCHARGE_DATE, APPOINTMENT,NOTE) 
	VALUES (10005, 13, '2022-02-27', '2022-02-28',0,'NOTE:');
INSERT INTO ADMISSION(PATIENT_ID, BED_ID, ADMISSION_DATE, DISCHARGE_DATE, APPOINTMENT,NOTE) 
	VALUES (10010, 6, '2023-03-10', '2023-04-02',0,'NOTE:');
INSERT INTO ADMISSION(PATIENT_ID, BED_ID, ADMISSION_DATE, DISCHARGE_DATE, APPOINTMENT,NOTE) 
	VALUES (10011, 11, '2022-11-03', '2022-11-21',1,'');
INSERT INTO ADMISSION(PATIENT_ID, BED_ID, ADMISSION_DATE, DISCHARGE_DATE, APPOINTMENT,NOTE) 
	VALUES (10016, 7, '2022-12-22', '2022-12-29',1,'NOTE:');
INSERT INTO ADMISSION(PATIENT_ID, BED_ID, ADMISSION_DATE, DISCHARGE_DATE, APPOINTMENT,NOTE) 
	VALUES (10020, 18, '2023-01-02', '2023-01-06',1,'');
INSERT INTO ADMISSION(PATIENT_ID, BED_ID, ADMISSION_DATE, DISCHARGE_DATE, APPOINTMENT,NOTE) 
	VALUES (10022, 5, '2023-01-25', '',1,'');
INSERT INTO ADMISSION(PATIENT_ID, BED_ID, ADMISSION_DATE, DISCHARGE_DATE, APPOINTMENT,NOTE) 
	VALUES (10024, 30, '2023-02-02', '2023-02-04',0,'NOTE:');
INSERT INTO ADMISSION(PATIENT_ID, BED_ID, ADMISSION_DATE, DISCHARGE_DATE, APPOINTMENT,NOTE) 
	VALUES (10025, 22, '2023-02-19', '',0,'NOTE:');
INSERT INTO ADMISSION(PATIENT_ID, BED_ID, ADMISSION_DATE, DISCHARGE_DATE, APPOINTMENT,NOTE) 
	VALUES (10027, 2, '2023-03-04', '2023-03-10',0,'NOTE:');
INSERT INTO ADMISSION(PATIENT_ID, BED_ID, ADMISSION_DATE, DISCHARGE_DATE, APPOINTMENT,NOTE) 
	VALUES (10029, 19, '2023-03-23', '',0,'NOTE:');
	
SELECT * FROM ADMISSION;
--INSERT RECORDS INTO FINANCIAL_STATUS

INSERT INTO FINANCIAL_STATUS ( FINANCIAL_TYPE)
VALUES ('PERSONAL');

INSERT INTO FINANCIAL_STATUS (FINANCIAL_TYPE)
VALUES ('CORPORATE');

INSERT INTO FINANCIAL_STATUS (FINANCIAL_TYPE)
VALUES ('PERSONAL');

INSERT INTO FINANCIAL_STATUS (FINANCIAL_TYPE)
VALUES ( 'PUBLIC');

INSERT INTO FINANCIAL_STATUS (FINANCIAL_TYPE)
VALUES ('CORPORATE');

SELECT * FROM FINANCIAL_STATUS;

--INSERT RECORDS INTO COST_CENTRE
INSERT INTO COST_CENTRE(DESCRIPTION)
VALUES ('Radiaology');

INSERT INTO COST_CENTRE (DESCRIPTION)
VALUES ('Room and Board');

INSERT INTO COST_CENTRE (DESCRIPTION)
VALUES ('Laboratory');

INSERT INTO COST_CENTRE (DESCRIPTION)
VALUES ('Room and Board');

INSERT INTO COST_CENTRE (DESCRIPTION)
VALUES ('Laboratory');

SELECT * FROM COST_CENTRE;

--INSERT RECORDS INTO ITEM

INSERT INTO ITEM (COST_CENTRE_ID,COST)
VALUES(2,710.00);

INSERT INTO ITEM (COST_CENTRE_ID,COST)
VALUES(4,690.00);

INSERT INTO ITEM (COST_CENTRE_ID,COST)
VALUES(1,780.00);

INSERT INTO ITEM (COST_CENTRE_ID,COST)
VALUES(3,400.00);

INSERT INTO ITEM (COST_CENTRE_ID,COST)
VALUES(2,380.00);

SELECT * FROM ITEM;

--INSERT RECORDS INTO BILL

INSERT INTO BILL(ADMISSION_ID,BILL_DATE)
VALUES(12,'2009-01-03');

INSERT INTO BILL(ADMISSION_ID,BILL_DATE)
VALUES(2 ,'2022-10-15');

INSERT INTO BILL(ADMISSION_ID,BILL_DATE)
VALUES(5,'2020-01-18');

INSERT INTO BILL(ADMISSION_ID,BILL_DATE)
VALUES(11,'2021-06-08');

INSERT INTO BILL(ADMISSION_ID,BILL_DATE)
VALUES(10,'2021-08-28');

SELECT * FROM BILL;

--INSERT RECORDS INTO CHARGE_ITEM

INSERT INTO CHARGE_ITEM(ITEM_CODE,BILL_ID,FINANCIAL_ID,ADMISSION_ID,DESCRIPTION,QUANTITY,UNIT_PRICE,DATE)
VALUES(2, 2, 1,3 , 'Blood pressure checkup' , 2 , 230.00,'2023-04-20');

INSERT INTO CHARGE_ITEM(ITEM_CODE,BILL_ID,FINANCIAL_ID,ADMISSION_ID,DESCRIPTION,QUANTITY,UNIT_PRICE,DATE)
VALUES(4, 3, 5, 10, 'CHEST X-RAY' , 3, 2000.00,'2022-06-27');

INSERT INTO CHARGE_ITEM(ITEM_CODE,BILL_ID,FINANCIAL_ID,ADMISSION_ID,DESCRIPTION,QUANTITY,UNIT_PRICE,DATE)
VALUES(1, 1, 4,2 , 'GLUCOSE' , 6, 250.00 ,'2021-04-20');

INSERT INTO CHARGE_ITEM(ITEM_CODE,BILL_ID,FINANCIAL_ID,ADMISSION_ID,DESCRIPTION,QUANTITY,UNIT_PRICE,DATE)
VALUES( 3, 5, 3,4 , 'CHEST X-RAY' , 2, 2500.00,'2021-03-01' );

INSERT INTO CHARGE_ITEM(ITEM_CODE,BILL_ID,FINANCIAL_ID,ADMISSION_ID,DESCRIPTION,QUANTITY,UNIT_PRICE,DATE)
VALUES(2, 2, 3,11 , 'Electrocardiogram test' , 1 , 500.00 ,'2021-07-26' );

SELECT * FROM CHARGE_ITEM;

--INSERT RECORDS INTO PAYMENT

INSERT INTO PAYMENT(BILL_ID,PAYMENT_DATE,PAID_AMOUNT)
VALUES( 2,' 2023-01-23', 2330.00);

INSERT INTO PAYMENT(BILL_ID,PAYMENT_DATE,PAID_AMOUNT)
VALUES( 1, '2022-04-29', 4000.00);

INSERT INTO PAYMENT(BILL_ID,PAYMENT_DATE,PAID_AMOUNT)
VALUES( 2, '2023-02-14', 1050.00);

INSERT INTO PAYMENT(BILL_ID,PAYMENT_DATE,PAID_AMOUNT)
VALUES( 3, '2021-07-24', 5090.00);

INSERT INTO PAYMENT(BILL_ID,PAYMENT_DATE,PAID_AMOUNT)
VALUES( 5, '2022-01-18', 800.00);

SELECT *FROM PAYMENT;

-- Insert records into PRESCRIPTION table 

INSERT INTO PRESCRIPTION(PHYSICIAN_ID, PATIENT_ID, PRES_DATE, PRES_MEDICATION, PRES_DOSAGE) 
	VALUES (1, 10019, '2022-02-07', 'Amoxillin', '250mg, 10mg/day');
INSERT INTO PRESCRIPTION(PHYSICIAN_ID, PATIENT_ID, PRES_DATE, PRES_MEDICATION, PRES_DOSAGE) 
	VALUES (4, 10003, '2023-04-06', 'Ibuprofen', '50 pills, 2 pills/day');
INSERT INTO PRESCRIPTION(PHYSICIAN_ID, PATIENT_ID, PRES_DATE, PRES_MEDICATION, PRES_DOSAGE) 
	VALUES (2, 10008, '2022-10-01', 'Viagara', '200mg, 50mg as needed');
INSERT INTO PRESCRIPTION(PHYSICIAN_ID, PATIENT_ID, PRES_DATE, PRES_MEDICATION, PRES_DOSAGE) 
	VALUES (9, 10015, '2022-12-09', 'Tylenol', '400mg, 10mg as needed');
INSERT INTO PRESCRIPTION(PHYSICIAN_ID, PATIENT_ID, PRES_DATE, PRES_MEDICATION, PRES_DOSAGE) 
	VALUES (4, 10010, '2023-03-16', 'Calcium Carbonate', '100 pills, 2 pills/day');
INSERT INTO PRESCRIPTION(PHYSICIAN_ID, PATIENT_ID, PRES_DATE, PRES_MEDICATION, PRES_DOSAGE) 
	VALUES (6, 10024, '2023-01-22', 'Cimzia', '100ml, 2 times/day');
INSERT INTO PRESCRIPTION(PHYSICIAN_ID, PATIENT_ID, PRES_DATE, PRES_MEDICATION, PRES_DOSAGE) 
	VALUES (4, 10027, '2023-02-12', 'Nitroglycerin', '20 pills, 1 pill as needed');

SELECT * FROM PRESCRIPTION;

-- Insert records into TEST table 

INSERT INTO TEST(PATIENT_ID, PHYSICIAN_ID, TEST_DATE, TEST_TYPE, RESULT) 
	VALUES (10002, 9, '2021-11-30', 'MRI', 'No significant change');
INSERT INTO TEST(PATIENT_ID, PHYSICIAN_ID, TEST_DATE, TEST_TYPE, RESULT) 
	VALUES (10005, 8, '2022-03-05', 'CAT', 'Benign lump');
INSERT INTO TEST(PATIENT_ID, PHYSICIAN_ID, TEST_DATE, TEST_TYPE, RESULT) 
	VALUES (10011, 4, '2022-03-11', 'CAT', 'Possible cancer');
INSERT INTO TEST(PATIENT_ID, PHYSICIAN_ID, TEST_DATE, TEST_TYPE, RESULT) 
	VALUES (10008, 5, '2022-04-26', 'Blood test', 'Anemia');
INSERT INTO TEST(PATIENT_ID, PHYSICIAN_ID, TEST_DATE, TEST_TYPE, RESULT) 
	VALUES (10013, 1, '2022-07-06', 'Stress test', 'No conclusion');
INSERT INTO TEST(PATIENT_ID, PHYSICIAN_ID, TEST_DATE, TEST_TYPE, RESULT) 
	VALUES (10021, 7, '2022-10-18', 'MRI', 'Possible blood clot');
INSERT INTO TEST(PATIENT_ID, PHYSICIAN_ID, TEST_DATE, TEST_TYPE, RESULT) 
	VALUES (10002, 8, '2023-01-25', 'Ultrasound', 'Pregnant');

SELECT * FROM TEST;
